### ISSUE TITLE
Rename file name, so can link static with Aspects.

### ISSUE THREAD

**Issue by CodeLife2012** [eleme/NVMAspects#5]

**Comment by meritozh** [comment]
是防止链接时重定义错误吗？加 -dead-strip 就可以了

**Comment by CodeLife2012** [comment]
@meritozh Test in a demo project, seems no conflict. Previous I think two same name object file will [conflict](https://stackoverflow.com/questions/9351132/two-files-of-the-same-name-give-linker-error-in-visual-studio) when link.

**Comment by meritozh** [comment]
Two same name symbols will cause link-time error. Linker accept two same name objects only if they have different path.

**Comment by CodeLife2012** [comment]
OK, close this.
